### ISSUE TITLE
De novo opening and closing reads file a lot

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#136]
https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/denovo_discovery/candidate_region.cpp#L126-L149

The above function is run once for every `CandidateRegion`

https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/map_main.cpp#L416-L426

If the reads file is large, this will take a considerable amount of time!

**Comment by mbhall88** [comment]
One obvious solution is to just create a file handle outside of the `for` loop and have `CandidateRegion::generate_read_pileup` take a file handle instead of a path. **But** I am worried this could cause a lot of problems when it comes to trying to multithread @leoisl ?

**Comment by mbhall88** [comment]
Now that I look at it, there is no reason that block https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/map_main.cpp#L416-L426

cant be moved to here

https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/map_main.cpp#L388-L392

and then we run de novo for all of the candidates within a pan-node.  

However, even with this change it still doesn't fix the fact that the read file is being opened for ever run of de novo...

**Comment by leoisl** [comment]
I agree that multi-threading over all candidate regions would be probably faster than multi-threading over pan-nodes. Is the processing of different candidate regions (even if they come from the same pan-node) independent? If so, it is easy to multi-thread. Otherwise, we should take care on how to synchronise.

Regarding the several and several traversals of the reads file, I am interested to know if this is indeed a bottleneck. For me, it seems so, but can you confirm it (either by your experience or some log)? In toy examples, this will probably not be an issue, as reads files are very small, so we would need to check if this is an issue in real datasets. Anyway, from what I understood, each read in `CandidateRegion::read_coordinates` has to be found in the reads file:

https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/denovo_discovery/candidate_region.cpp#L132-L134

I think this can be potentially slow, since it translates into many file read operations (e.g. if we want to access the last read of the file, we have to read and skip all the other reads). I think positioning the file pointer directly where the read is, is way faster. I think we can accomplish this with http://www.htslib.org/doc/faidx.html . We can use their C API to do so: http://samtools.sourceforge.net/samtools/faidx/index.html . Like this we just move the file pointer to the read, and do only one read operation per read. We will still need to open the file for each candidate region, but I believe that using the index will solve the performance issues...

What do you think? Do you see a better solution?

**Comment by mbhall88** [comment]
> I agree that multi-threading over all candidate regions would be probably faster than multi-threading over pan-nodes. Is the processing of different candidate regions (even if they come from the same pan-node) independent? If so, it is easy to multi-thread. Otherwise, we should take care on how to synchronise.

Yes each candidate region (should) be independent, even if it's from the same pan-node.
> Regarding the several and several traversals of the reads file, I am interested to know if this is indeed a bottleneck. For me, it seems so, but can you confirm it (either by your experience or some log)? In toy examples, this will probably not be an issue, as reads files are very small, so we would need to check if this is an issue in real datasets. Anyway, from what I understood, each read in `CandidateRegion::read_coordinates` has to be found in the reads file:
> 
> https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/denovo_discovery/candidate_region.cpp#L132-L134
> 
> I think this can be potentially slow, since it translates into many file read operations (e.g. if we want to access the last read of the file, we have to read and skip all the other reads). I think positioning the file pointer directly where the read is, is way faster. I think we can accomplish this with http://www.htslib.org/doc/faidx.html . We can use their C API to do so: http://samtools.sourceforge.net/samtools/faidx/index.html . Like this we just move the file pointer to the read, and do only one read operation per read. We will still need to open the file for each candidate region, but I believe that using the index will solve the performance issues...
> 
> What do you think? Do you see a better solution?

I believe this is to do with the way @rmcolq handles fastaq files. Ie the read id is effectively it's line number in the file. As if your reads are sorted you should only need to parse the fastaq file once.

**Comment by leoisl** [comment]
> I believe this is to do with the way @rmcolq handles fastaq files. Ie the read id is effectively it's line number in the file. As if your reads are sorted you should only need to parse the fastaq file once.

Indeed, in this function, pandora parses the fastaq file once per candidate region, even if we have several `read_coodinates`, since these are sorted by `id`.  But do you think even this is slow?  If I understood correctly, if we have 5 `read_coordinates` for a candidate region, and the maximum `read_coordinate.id` is 50000, then we will have to read 50000 reads from the fastaq file. 49995 of them will be read, but discarded here:
https://github.com/rmcolq/pandora/blob/5356466d645172171df24009612153b65716176c/src/fastaq_handler.cpp#L148-L153

I guess instead of this we just position the file pointer where the 5 reads to be read are and do only 5 read operations. But to do this, we need the index. If parsing the fastaq as it is done now is not slow, then  we can leave it like this.

**Comment by mbhall88** [comment]
Yes, I see what you mean. We had previously spoken about changing our fast{aq} handling process but never really got around to doing it.  https://github.com/rmcolq/pandora/issues/74#issuecomment-432183107

Maybe now is the best time given you are in the process of trying to speed everything up. And your suggestion of htslib obviously makes a lot of sense.  

Best to get input from @rmcolq and @iqbal-lab though.

**Comment by rmcolq** [comment]
My memory is that when we were writing this bit of code with Robyn, we had the file handle open and passed it as an argument to extract pileups for each region. Because the regions were sorted by read, we only opened the file once and only looped through the file once. 

To parallelize, one option is to divide the regions into chunks, and open the file once per chunk of regions. Or the other option is to use a library for fastaq handling. My thoughts about on the external library: please check if it can handle the prg-like fasta first. And chat to Zam about the pros/cons of including yet another external library as a dependancy.

**Comment by iqbal-lab** [comment]
various comments here

- do we know this opening and closing is actually slow? i completely get and agree it's inefficient to open/close too much, but i'm wondering if we empirically know it is hurting us
- indexing the reads makes a lot of sense; htslib is obviously solid but also changes reasonably often and might be a maintenance burden there,plus rachels question of whether it will allow prg-like fasta
- Having said all that I generally favour fixing correctness first and then speed. For the de novo component, i think we're pretty sure the actual path traversal stuff is solid, but we don't understand where we lose  our 50% of recall. currently we know it's not due to explosion of too many paths to enumerate, so possibly/probably due to our decision process for where to do de novo. So my temptation right now is to suggest we hold off addressing this issue til that is dealt with, both in terms of pandora priorities and leandro priorities. ie if leandro was out of work and looking for something to do, and michael was still where he is now, i'd suggest we see if there is any mileage in collaborating on that. Maybe there isn't, but that's what i'd ask.

**Comment by iqbal-lab** [comment]
is there a reason we can't load up the slice of reads that overlap the gene into memory, and then deal with this all in memory? one of the things we've proposed doing, to enable compare to work across a cluster with one gene per node, is at quasimap time, to dump a file of the subreads that overlap each gene. if we did that, then during de novo you'd just pull up the reads for that gene. does that sound viable?

**Comment by mbhall88** [comment]
*More context to this issue*  

Running `pandora map` with `--discover` on a 3.3Gb nanopore fastq file takes a very long time. The long time is likely, mostly attributable to the opening and closing of the file. An example from the log file

```
[2019-06-28 21:46:09.390015] [0x00002b66e78653c0] [debug]   Open fastaq file/hps/nobackup/research/zi/mbhall/Pandora_variation/Analysis/ST38/ST38.fastq.gz
[2019-06-28 21:46:23.531611] [0x00002b66e78653c0] [debug]   Close fastaq file
```
 This means it is taking ~15s to open the read file **for each candidate region**. The consequence of this is that if we run denovo discovery on 10,000 candidate regions (a likely scenario in previous samples) then **41.6 hours of `pandora map` is spent just opening the read file over and over again**.

**Comment by mbhall88** [comment]
> is there a reason we can't load up the slice of reads that overlap the gene into memory, and then deal with this all in memory? one of the things we've proposed doing, to enable compare to work across a cluster with one gene per node, is at quasimap time, to dump a file of the subreads that overlap each gene. if we did that, then during de novo you'd just pull up the reads for that gene. does that sound viable?


Having all the reads in memory could be pretty dangerous no? I mean some of my nanopore fastq files are > 20Gb.

**Comment by iqbal-lab** [comment]
the whole point is you slice the reads where they overlap a gene, and write that to file. then you only load into memory the bits of the reads that overlap the gene. so thats ~1kb long, 100x, not much.
This also then allows massive parallelisation by gene - at least in terms of RAM, each node in a cluster could do 10,000 samples all on the same gene. granted, this naive implementation would mean each node would be opening 10,000 files, so maybe we would batch genes, but the basic idea is you allow parallelising by slicing reads where they overlap genes

**Comment by iqbal-lab** [comment]
it's like loading the gene pileup into RAM

**Comment by iqbal-lab** [comment]
the other thing one could do is this. When quasimapping a sample, you write all these 5000 files.  then at the end, you basically cat them into one file, and store an index which says reads 1..99 are for gene 1, 100-134 are for gene 27,...etc, allowing you later on to seek to the right place to pull out precisely the reads you want. you then delete your 5000 files. 
The only difference  to the above is that you then have one file per sample, not 5000 per sample.
So this is  better for the filesystem in terms of numbers of files. On the other hand when you have 5000 nodes each processing one gene for 10,000 samples, each node has  needs to open all of the 10000 per-sample fastqs, each pulling out their own gene.

ok i take it all back, maybe best to have loads of files in a tree of directories.

**Comment by leoisl** [comment]
I tried to find other alternative implementations, and I only see one, which is easier to implement, consume less disk space, and probably faster if a SSD is used, but slower if HDD is used. However, I don't think we should take the decision hoping the user would store files in a SSD...

As such, I think the best solution is Zam's idea of slicing the reads where they overlap a gene, and writing this to a tree of directories. I'd propose we go for this implementation, if you agree.

**Comment by iqbal-lab** [comment]
It does mean we (at least temporarily) double disk usage. I think we live with it. But we could contemplate discarding qualities. Also could think of cutting the sliced reads at low quality bases so they don't add noise to de novo

**Comment by leoisl** [comment]
Agreed, I think removing the noise can be indeed good to improve results!

+1 for this idea!

I think we should prioritise this, hoping to get this solved next week!
