### ISSUE TITLE
Failed to create out_dir due to boost corner case

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#139]
If the current directory is passed to `-o`  as `.` in `map` then the program fails with error message

```
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::create_directory: No such file or directory
```

Looking into [this]https://stackoverflow.com/questions/42200000/boostfilesystemcreate-directories-fails, it appears that `boost::filesystem::create_directories` cannot handle this corner case (using `$(pwd)` does however work).

We need to handle the case where the user passes `.`

**Comment by leoisl** [comment]
I guess this can be solved by converting the path passed by `-o` into its absolute path (see https://wandbox.org/permlink/nCcK6yxJTYMo0kzZ ).  I think we should convert the argument right away, e.g. in https://github.com/rmcolq/pandora/blob/master/src/map_main.cpp#L110 .

More in general, I really think we should only use absolute paths to avoid any path issues. This means every path passed by any argument should be converted to its absolute form and we should only use `boost::filesystem::path` to represent paths instead of e.g. `std::string` in https://github.com/rmcolq/pandora/blob/master/src/compare_main.cpp#L99 . When having such issues, I usually worked only with canonical paths (https://www.boost.org/doc/libs/1_70_0/libs/filesystem/doc/reference.html#canonical-path), but we can't convert a non-existing path into its canonical form... I guess absolute paths are enough though.

I can make this change throughout the whole codebase if you wish, but just in ~2 weeks...

**Comment by mbhall88** [comment]
Agreed. Making it a path straight away would be the best way.  A couple of functions may need to have their signature changed, but shouldn't be an issue.
That would be great if you're able to do this. 2 weeks is fine, there is no rush as it is easy enough to work around anyways.
