### ISSUE TITLE
Release build tests don't all pass

### ISSUE THREAD

**Issue by mbhall88** [rmcolq/pandora#166]

**Comment by rmcolq** [comment]
Would this still be the case if we removed the EXPECT_DEATH tests which check particular asserts?

**Comment by leoisl** [comment]
Sorry for the long post, many things here as I started reading how to deal with this.

* Release build optimises for speed, so `-DNDEBUG` flag is passed when building, which disable all asserts. We can simply remove this flag, which will make all tests pass in the Release build, but then we would surely lose performance, since the code will then run all the asserts.

* It seems that the best thing to do is to develop in Debug build (which we do now), but test the Release build (we test the Debug build only), since it is ultimately what will be run outside of the development environment (see https://stackoverflow.com/questions/3416665/unit-testing-on-a-build-server-release-or-debug-code). Some compiler optimisations might make the Debug executable and Release executable behave slightly different, which might cause bugs (e.g. https://stackoverflow.com/questions/20484449/unit-test-passes-in-debug-build-but-fails-in-release-build ). **So my vote is on testing the Release executable, not the Debug one, to make sure the code which will be executed by others is fine.**

However, as said, to test the Release build we have to enable all asserts, which make us lose performance. There is a reason why `cmake` disable asserts in Release mode: asserts should not be in the Release executable. We need to revisit the `assert`s in pandora. I agree with this post: https://stackoverflow.com/a/409981/5264075 . Assertions are for conditions that should **never** happen when running the code - it is solely to catch developer errors, not user/data errors, and thus can be safely disabled in Release mode, e.g. asserting that the node coverage is the same as the number of reads in a `pangenome::Node` (this error cannot be caused by the user or the data, but only by programmers misusing the `update_node_info_with_this_read` function):

https://github.com/rmcolq/pandora/blob/ef6efe1d9e8231a45b2b3e33f5acc614389d1c7c/src/pangenome/pangraph.cpp#L69-L73

Exceptions are used for run-time error conditions, which could potentially happen when running the tool due to user/data problems, and must be enabled in Release mode, e.g.: the user passing a window size smaller than the kmer size:
https://github.com/rmcolq/pandora/blob/ef6efe1d9e8231a45b2b3e33f5acc614389d1c7c/src/compare_main.cpp#L269

This assert above also is very serious - in the current Release build, we allow the user to do this without any error message.

My impression is that the vast majority of the asserts in pandora deal with runtime errors, not developer errors. Runtime errors assertions **must** be in the executable. So I'd vote for: **1) quick fix: enable asserts in Release mode; 2) long term, better fix: refactor assert statements, splitting them into asserts and exceptions, asserts are disabled in Release mode, exceptions are enabled.**

**Comment by leoisl** [comment]
Solved in [v0.8.0](https://github.com/rmcolq/pandora/releases/tag/0.8.0)
