### ISSUE TITLE
Optimise writes

### ISSUE THREAD

**Issue by rmcolq** [rmcolq/pandora#20]
Use \n rather than endl and write longer strings less often, based on Martin's advice about the performance hit.

**Comment by rffrancon** [comment]
@rmcolq @mbhall88 I think we should close this issue. If logging is a performance concern, we simply shouldn't log frequently (i.e. log every 100th iteration), log a smaller amount of data, or avoid logging in performance intensive parts altogether.

Boost logging may use `std::endl` or it may not, that's not our problem. Every intentional optimization should be guided by profiling.
