### ISSUE TITLE
warnings while doing VCF calls with pandora map

### ISSUE THREAD

**Issue by LilithElina** [rmcolq/pandora#206]
I finally got around to try the `--genotype` argument in `pandora map` and while I got the expected two VCF files as output, I also had a lot of warnings in the console. They were always these two for different (probably all, I didn't count) genes:

`[2020-01-08 09:32:57.905378] [0x00007fd741ceff80] [warning] Input vcf_ref path was too short to be the ref for PRG GC00002025`

`[2020-01-08 09:32:57.905389] [0x00007fd741ceff80] [warning] Could not find reference sequence for GC00002025 in the PRG so using the consensus path`

They occur after this line:

`Wed Jan  8 09:32:57 2020 Find PRG paths and write to files:`

This did not happen when I used `pandora map` without the `--genotype` option. What does it mean?

**Comment by rmcolq** [comment]
These warnings can safely be ignored. They are being triggered by the default user behaviour which is not to provide a VCF reference. The first of these is already fixed in a pull request I'm waiting to merge in. We will update the code to stop the second being triggered also (or at least call it something other than warning)

**Comment by LilithElina** [comment]
Thank you!
